[mypy]
exclude = (^test_.*\.py$|tests/|^guess_.*_app\.py$)
python_version = 3.13

# Forces you to define types for all function signatures
disallow_untyped_defs = True

# Prevents the use of 'Any' in explicit type annotations
disallow_any_explicit = True

# Provides more detail about where the error is occurring in the code structure
show_error_context = True

# Makes the output easier to read with colors and source code snippets
pretty = True

[mypy-views]
ignore_errors = True